### PR TITLE
Fix assertion in VirtualScope

### PR DESCRIPTION
**Pull request by thezhangwei**
Do you mind giving it a try?
It still crashes in my docker image but maybe for a different issue.
There's not much debug I can do in the docker image. Maybe you can educate me on that. :)

### CODE REVIEW

**Comment by wisechengyi** [comment]
Thanks Wei. I'm currently out of town, but will try it out this weekend.

To debug in docker, you should be to just run redex with --gdb, which was
also suggested by Justin.

-Yi

**Comment by thezhangwei** [comment]
It's kind of weird the gdb in the docker image doesn't give me stack trace or program location. I wasn't able to set breakpoint where I wanted either. I think the crash right now is in the InlineHelper. So it looks like a different crash now..

**Comment by wisechengyi** [comment]
Could you post the stacktrace of the crash you saw? 

It would be good to rebase your change on top of latest master and see if the crash still occurs. It's essentially the redex repo in docker container, so you should be able to perform any git operations.

**Comment by thezhangwei** [comment]
There's no stack trace on the docker image. I tried rebasing. I don't think the latest master builds on Ubuntu or the docker image... Sorry not very familiar with the docker thing. I guess you need a real environment to debug it. My patch for the assertion error is in the pipe and coming soon though. Yeah the open source build can be better than this...

**Comment by wisechengyi** [comment]
Docker should be real enough, as far as it can reproduce the same error we are seeing in any other centos box. But yeah, not having stacktrace is annoying. I will take a look this weekend as well, and see if we can dig deeper on that. Thanks for the help @thezhangwei!

**Comment by justinjhendrick** [comment]
I'm about to add a patch that should help with debugging. Including the linker flag `-rdynamic` should get you function names in crashes (outside of the debugger)

**Pull request closed without merging**
